SAMPLE_1 = {
    "title": "Trump immigration suspension under fire as experts say economic benefits unclear",
    "publishedAt": "None",
    "url": "https://abcnews.go.com/Politics/trump-immigration-suspension-fire-experts-economic-benefits-unclear/story?id=70383675",
    "urlToImage": None,
    "description": "",
    "content": "",
    "author": "['Abc News', 'Quinn Owen', 'April', 'Min Read']",
    "articleText": "Trump immigration suspension under fire as experts say economic benefits unclear The suspension was framed as a vital component of helping U.S. workers recover.\n\nWith visa office closures and international travel restrictions still in place, experts say the economic benefits of President Donald Trump’s immigration suspension last week are uncertain, at best, while thousands of prospective immigrants still stand to suffer the consequences.\n\nAlthough the suspension was filled with broad exemptions and does not include current visa holders or those already in the U.S., the Migration Policy Institute estimates 26,000 would-be green card applicants would be blocked each month.\n\nOver the weekend, a coalition of advocacy groups filed an emergency request to halt Trump’s directive. It was the latest move in a 2019 case, stemming from when the White House sought to ban immigrants who couldn’t prove their ability to acquire health insurance within a month of arriving in the U.S.\n\nAttorneys with the American Immigration Lawyers Association requested a hold on the recent suspension order while the courts continue to decide the fate of the health insurance restrictions.\n\nThe White House framed the immigration suspension as a vital component of helping the economy and American workers recover, but it could have the opposite effect.\n\nImmigrants already in the U.S. and those who already have certain visas can still obtain permanent residency. The suspension applies only to green card applicants from outside the country and primarily targets to those looking to settle down in the U.S. permanently through a family connection, according to MPI estimates.\n\nThat leaves the possibility of employment-based visa slots opening up as a result of the suspension.\n\n\"It's going to actually remake the body of immigrants coming to the United States,\" immigration attorney Loren Locke told Law 360.\n\nPresident Donald Trump arrives with Vice President Mike Pence for the daily coronavirus task force briefing at the White House in Washington, April 22, 2020. Jonathan Ernst/Reuters\n\nTune into ABC at 1 p.m. ET and ABC News Live at 4 p.m. ET every weekday for special coverage of the novel coronavirus with the full ABC News team, including the latest news, context and analysis.\n\n\"President Trump claims he signed it in order to protect the economy in the wake of the coronavirus outbreak, but the reality is that our economic recovery will depend on immigrants,\" said Esther Sung, a senior attorney involved in the 2019 case.\n\nThat view is shared, in part, by Rutgers economics professor Jennifer Hunt. She told ABC News that an influx of workers into critical sectors of the economy could boost per capita GDP.\n\n\"It would be kind of a shot in the arm,\" Hunt said.\n\nOn-going travel restrictions and the closure of foreign visa offices still pose the greatest barrier to legal immigration in the age of coronavirus. Economists and labor experts, including Hunt, say those factors would override any attempt to assess the economic impacts of the restrictions.\n\n\"It’s very hard for me to see the direct correlation in terms of immediate and practical positive impact on displaced U.S. workers,\" said Caroline Tang, an Austin-based attorney who advises companies on work authorization for immigrants.\n\nTang said the bar for employers to obtain work authorization for visa holders is already high enough, referring to specific requirements for prioritizing U.S. citizens.\n\nResearchers have identified some connection between more immigrants settled in the country and economic growth under normal circumstances, but the results are mixed.\n\nFor example, a 2017 report by the economics firm Moody Analytics and ProPublica found that for every 1% increase in the U.S. population, the gross domestic product rises by 1.5%. While a 2018 study from Stanford University’s Hoover Institution confirms that \"positive relationship\" generally, but found variations and some negative impacts to U.S.-born employment rates in its state-by-state review.\n\nResearchers studying the large population of foreign-born workers in South Africa said it likely had a positive impact on per capita GDP.\n\n\"Foreign-born workers also generated additional employment for native-born workers,\" according to the 2018 Organisation for Economic Co-operation and Development report.\n\nWhat to know about the coronavirus:\n\nHow it started and how to protect yourself: Coronavirus explained\n\nWhat to do if you have symptoms: Coronavirus symptoms\n\nTracking the spread in the U.S. and worldwide: Coronavirus map",
    "source": {
        "name": "ABC News",
        "id": None,
        "description": None,
        "url": "https://abcnews.go.com",
        "category": None,
        "language": None,
        "country": None
    }
}

SAMPLE_1_RESULT = {
	"title": "Trump immigration suspension under fire as experts say economic benefits unclear",
	"publishedAt": "None",
	"url": "https://abcnews.go.com/Politics/trump-immigration-suspension-fire-experts-economic-benefits-unclear/story?id=70383675",
	"urlToImage": None,
	"description": "",
	"content": "",
	"author": "['Abc News', 'Quinn Owen', 'April', 'Min Read']",
	"articleText": "Trump immigration suspension under fire as experts say economic benefits unclear The suspension was framed as a vital component of helping U.S. workers recover.\n\nWith visa office closures and international travel restrictions still in place, experts say the economic benefits of President Donald Trump\u2019s immigration suspension last week are uncertain, at best, while thousands of prospective immigrants still stand to suffer the consequences.\n\nAlthough the suspension was filled with broad exemptions and does not include current visa holders or those already in the U.S., the Migration Policy Institute estimates 26,000 would-be green card applicants would be blocked each month.\n\nOver the weekend, a coalition of advocacy groups filed an emergency request to halt Trump\u2019s directive. It was the latest move in a 2019 case, stemming from when the White House sought to ban immigrants who couldn\u2019t prove their ability to acquire health insurance within a month of arriving in the U.S.\n\nAttorneys with the American Immigration Lawyers Association requested a hold on the recent suspension order while the courts continue to decide the fate of the health insurance restrictions.\n\nThe White House framed the immigration suspension as a vital component of helping the economy and American workers recover, but it could have the opposite effect.\n\nImmigrants already in the U.S. and those who already have certain visas can still obtain permanent residency. The suspension applies only to green card applicants from outside the country and primarily targets to those looking to settle down in the U.S. permanently through a family connection, according to MPI estimates.\n\nThat leaves the possibility of employment-based visa slots opening up as a result of the suspension.\n\n\"It's going to actually remake the body of immigrants coming to the United States,\" immigration attorney Loren Locke told Law 360.\n\nPresident Donald Trump arrives with Vice President Mike Pence for the daily coronavirus task force briefing at the White House in Washington, April 22, 2020. Jonathan Ernst/Reuters\n\nTune into ABC at 1 p.m. ET and ABC News Live at 4 p.m. ET every weekday for special coverage of the novel coronavirus with the full ABC News team, including the latest news, context and analysis.\n\n\"President Trump claims he signed it in order to protect the economy in the wake of the coronavirus outbreak, but the reality is that our economic recovery will depend on immigrants,\" said Esther Sung, a senior attorney involved in the 2019 case.\n\nThat view is shared, in part, by Rutgers economics professor Jennifer Hunt. She told ABC News that an influx of workers into critical sectors of the economy could boost per capita GDP.\n\n\"It would be kind of a shot in the arm,\" Hunt said.\n\nOn-going travel restrictions and the closure of foreign visa offices still pose the greatest barrier to legal immigration in the age of coronavirus. Economists and labor experts, including Hunt, say those factors would override any attempt to assess the economic impacts of the restrictions.\n\n\"It\u2019s very hard for me to see the direct correlation in terms of immediate and practical positive impact on displaced U.S. workers,\" said Caroline Tang, an Austin-based attorney who advises companies on work authorization for immigrants.\n\nTang said the bar for employers to obtain work authorization for visa holders is already high enough, referring to specific requirements for prioritizing U.S. citizens.\n\nResearchers have identified some connection between more immigrants settled in the country and economic growth under normal circumstances, but the results are mixed.\n\nFor example, a 2017 report by the economics firm Moody Analytics and ProPublica found that for every 1% increase in the U.S. population, the gross domestic product rises by 1.5%. While a 2018 study from Stanford University\u2019s Hoover Institution confirms that \"positive relationship\" generally, but found variations and some negative impacts to U.S.-born employment rates in its state-by-state review.\n\nResearchers studying the large population of foreign-born workers in South Africa said it likely had a positive impact on per capita GDP.\n\n\"Foreign-born workers also generated additional employment for native-born workers,\" according to the 2018 Organisation for Economic Co-operation and Development report.\n\nWhat to know about the coronavirus:\n\nHow it started and how to protect yourself: Coronavirus explained\n\nWhat to do if you have symptoms: Coronavirus symptoms\n\nTracking the spread in the U.S. and worldwide: Coronavirus map",
	"source": {
		"name": "ABC News",
		"id": None,
		"description": None,
		"url": "https://abcnews.go.com",
		"category": None,
		"language": None,
		"country": None
	},
	"ner": [{
		"word": "Trump",
		"entity": "PERSON",
		"tool": "transformer",
		"confidence": 0.9850142598152161
	}, {
		"word": "US.",
		"entity": "LOC",
		"tool": "transformer",
		"confidence": 0.854858418305715
	}, {
		"word": "DonaldTrump",
		"entity": "PERSON",
		"tool": "transformer",
		"confidence": 0.9986022114753723
	}, {
		"word": "US",
		"entity": "LOC",
		"tool": "transformer",
		"confidence": 0.9995371103286743
	}, {
		"word": "MigrationPolicyInstitute",
		"entity": "ORG",
		"tool": "transformer",
		"confidence": 0.9992368370294571
	}, {
		"word": "Trump",
		"entity": "PERSON",
		"tool": "transformer",
		"confidence": 0.99837726354599
	}, {
		"word": "WhiteHouseUS",
		"entity": "LOC",
		"tool": "transformer",
		"confidence": 0.9844733327627182
	}, {
		"word": "AmericanImmigrationLawyersAssociation",
		"entity": "ORG",
		"tool": "transformer",
		"confidence": 0.9990341663360596
	}, {
		"word": "WhiteHouse",
		"entity": "LOC",
		"tool": "transformer",
		"confidence": 0.9964399933815002
	}, {
		"word": "American",
		"entity": "MISC",
		"tool": "transformer",
		"confidence": 0.9989724159240723
	}, {
		"word": "USUS",
		"entity": "LOC",
		"tool": "transformer",
		"confidence": 0.9993963837623596
	}, {
		"word": "MPI",
		"entity": "ORG",
		"tool": "transformer",
		"confidence": 0.9886887669563293
	}, {
		"word": "UnitedStates",
		"entity": "LOC",
		"tool": "transformer",
		"confidence": 0.9994847774505615
	}, {
		"word": "LorenLocke",
		"entity": "PERSON",
		"tool": "transformer",
		"confidence": 0.9995968341827393
	}, {
		"word": "Law360",
		"entity": "ORG",
		"tool": "transformer",
		"confidence": 0.9595861732959747
	}, {
		"word": "DonaldTrumpMikePence",
		"entity": "PERSON",
		"tool": "transformer",
		"confidence": 0.9984845042228698
	}, {
		"word": "WhiteHouseWashington",
		"entity": "LOC",
		"tool": "transformer",
		"confidence": 0.9963108698527018
	}, {
		"word": "JonathanErnst",
		"entity": "PERSON",
		"tool": "transformer",
		"confidence": 0.9810327887535095
	}, {
		"word": "ReutersTuABCABCNewsLiveronaABCNews",
		"entity": "ORG",
		"tool": "transformer",
		"confidence": 0.8678140997886657
	}, {
		"word": "Trump",
		"entity": "PERSON",
		"tool": "transformer",
		"confidence": 0.9934247136116028
	}, {
		"word": "rona",
		"entity": "ORG",
		"tool": "transformer",
		"confidence": 0.5108810663223267
	}, {
		"word": "Esther",
		"entity": "PERSON",
		"tool": "transformer",
		"confidence": 0.973687469959259
	}, {
		"word": "Rutgers",
		"entity": "ORG",
		"tool": "transformer",
		"confidence": 0.9920168519020081
	}, {
		"word": "JenniferHunt",
		"entity": "PERSON",
		"tool": "transformer",
		"confidence": 0.9741330444812775
	}, {
		"word": "SheABCNews",
		"entity": "ORG",
		"tool": "transformer",
		"confidence": 0.7636726399262747
	}, {
		"word": "U.S.",
		"entity": "GPE",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "Donald Trump",
		"entity": "PERSON",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "last week",
		"entity": "DATE",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "thousands",
		"entity": "CARDINAL",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "U.S.",
		"entity": "GPE",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "the Migration Policy Institute",
		"entity": "ORG",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "26,000",
		"entity": "CARDINAL",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "each month",
		"entity": "DATE",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "the weekend",
		"entity": "DATE",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "Trump",
		"entity": "PERSON",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "2019",
		"entity": "DATE",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "the White House",
		"entity": "ORG",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "a month",
		"entity": "DATE",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "U.S.",
		"entity": "GPE",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "the American Immigration Lawyers Association",
		"entity": "ORG",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "The White House",
		"entity": "ORG",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "American",
		"entity": "NORP",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "Immigrants",
		"entity": "PERSON",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "U.S.",
		"entity": "GPE",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "U.S.",
		"entity": "GPE",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "MPI",
		"entity": "ORG",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "the United States",
		"entity": "GPE",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "Loren Locke",
		"entity": "PERSON",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "360",
		"entity": "CARDINAL",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "Donald Trump",
		"entity": "PERSON",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "Mike Pence",
		"entity": "PERSON",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "the White House",
		"entity": "FAC",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "Washington",
		"entity": "GPE",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "April 22, 2020",
		"entity": "DATE",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "Jonathan Ernst/Reuters",
		"entity": "PERSON",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "Tune",
		"entity": "ORG",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "ABC",
		"entity": "ORG",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "1 p.m. ET",
		"entity": "TIME",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "ABC News Live",
		"entity": "ORG",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "4 p.m.",
		"entity": "TIME",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "ABC News",
		"entity": "ORG",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "Trump",
		"entity": "PERSON",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "Esther Sung",
		"entity": "PERSON",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "2019",
		"entity": "DATE",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "Jennifer Hunt",
		"entity": "PERSON",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "ABC News",
		"entity": "ORG",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "Hunt",
		"entity": "PERSON",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "Hunt",
		"entity": "PERSON",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "U.S.",
		"entity": "GPE",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "Caroline Tang",
		"entity": "PERSON",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "Austin",
		"entity": "GPE",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "Tang",
		"entity": "PERSON",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "U.S.",
		"entity": "GPE",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "2017",
		"entity": "DATE",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "Moody Analytics",
		"entity": "ORG",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "ProPublica",
		"entity": "ORG",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "1%",
		"entity": "PERCENT",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "U.S.",
		"entity": "GPE",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "1.5%",
		"entity": "PERCENT",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "2018",
		"entity": "DATE",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "Stanford University\u2019s Hoover Institution",
		"entity": "ORG",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "South Africa",
		"entity": "GPE",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "the 2018 Organisation for Economic Co-operation and Development",
		"entity": "ORG",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "Coronavirus",
		"entity": "ORG",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "U.S.",
		"entity": "GPE",
		"tool": "spacy",
		"confidence": None
	}, {
		"word": "Coronavirus",
		"entity": "ORG",
		"tool": "spacy",
		"confidence": None
	}]
}